#!/usr/bin/env tsx

/**
 * Development Setup Script
 * 
 * This script helps set up the development environment without Redis
 * and with minimal configuration for quick testing.
 */

import fs from 'fs';
import path from 'path';

const envTemplate = `# Development Environment Configuration
# Generated by setup-dev.ts

# Database (Required)
DATABASE_URL="postgresql://username:password@localhost:5432/meetbotai"
DIRECT_URL="postgresql://username:password@localhost:5432/meetbotai"

# JWT Secret (Required)
JWT_SECRET="dev-secret-key-change-in-production"

# Redis (Optional - commented out for development without Redis)
# REDIS_URL="redis://localhost:6379"

# Storage (Optional)
# AWS_ACCESS_KEY_ID="your-access-key"
# AWS_SECRET_ACCESS_KEY="your-secret-key"
# AWS_REGION="us-east-1"
# AWS_S3_BUCKET="meetbotai-recordings"

# AI Services (Optional)
# OPENAI_API_KEY="your-openai-key"
# GOOGLE_AI_API_KEY="your-gemini-key"

# Development Settings
NODE_ENV="development"
PORT="5000"
HOST="0.0.0.0"
ENABLE_SWAGGER="true"
`;

function setupDevEnvironment() {
  console.log('🔧 Setting up development environment...\n');

  const envPath = path.join(__dirname, '..', '.env');
  
  if (fs.existsSync(envPath)) {
    console.log('⚠️  .env file already exists');
    console.log('   If you want to reset it, delete .env and run this script again\n');
  } else {
    fs.writeFileSync(envPath, envTemplate);
    console.log('✅ Created .env file with development defaults\n');
  }

  console.log('📝 Next steps:');
  console.log('   1. Update DATABASE_URL in .env with your PostgreSQL connection');
  console.log('   2. Run: npm run db:push (to create database tables)');
  console.log('   3. Run: npm run db:setup (to create admin user)');
  console.log('   4. Run: npm run dev (to start the server)\n');

  console.log('💡 Optional Redis setup:');
  console.log('   - Install Redis: https://redis.io/docs/getting-started/installation/');
  console.log('   - Uncomment REDIS_URL in .env');
  console.log('   - Restart the server for background job support\n');

  console.log('🎉 Development environment ready!');
}

if (require.main === module) {
  setupDevEnvironment();
}

export { setupDevEnvironment };
